services:
  - type: web
    name: cafe-website
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      npm install
      npm run build
      php artisan storage:link
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://cafe-website.onrender.com
      - key: VITE_APP_URL
        value: https://cafe-website.onrender.com
      - key: DB_CONNECTION
        value: sqlite
